name: Hi Mascot
on: push
env:
  mascot: "Workflow Mascot"

jobs:
  windows_job:
    runs-on: windows-latest
    steps:
      - run: echo 'Hi ${{ env.mascot }}'  
      - run: echo 'Hi ${{ env.mascot }}'  
        env:
          mascot: "Windows Octocat"
  linux_job:
    runs-on: ubuntu-latest
    env:
      mascot: "Linux Octocat"
    steps:
      - run: echo 'Hi ${{ env.mascot }}'
