name: Super Linter workflow

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code 
    
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
