name: Hi Mascot

on:
  workflow_dispatch:

env:
  mascot: "Top level Mascot"

jobs:
  windows_job:
    runs-on: windows-latest
    steps:
      - name: top level
        run: echo 'Hi ${{ env.mascot }}'  
      - name: local level windows
        run: echo 'Hi ${{ env.mascot }}'  
        env:
          mascot: "Windows Octocat"
  linux_job:
    runs-on: ubuntu-latest
    env:
      mascot: "Linux Octocat"
    steps:
      - name: job level linux
        run: echo 'Hi ${{ env.mascot }}'  
